name: TelegramBot-Live-24/7

on:
  workflow_dispatch: # يتيح لك تشغيله يدوياً
  schedule:
    - cron: '0 */6 * * *' # سيعيد تشغيل نفسه كل 6 ساعات لضمان الاستمرارية

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # تأكد أنها نفس نسخة مشروعك

      - name: Run Bot
        run: dotnet run
