
  name: TelegramBot-Live-24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    # تغيير النظام من ubuntu إلى windows هو مفتاح الحل لمشروعك
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget restore mybottelegrame.csproj

      - name: Build Project
          # بناء المشروع باستخدام MSBuild المتوافق مع إصدارات ويندوز القديمة
        run: msbuild mybottelegrame.csproj /p:Configuration=Release

      - name: Run Bot
        # تشغيل ملف الـ exe الناتج من عملية البناء
        run: |
          cd bin/Release
          start mybottelegrame.exe 
